services:
  - type: web
    name: my-discord-bot
    env: node
    plan: free
    branch: main
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node index.js"
    autoDeploy: true
    healthCheckPath: /
